# Generated by Django 3.1.1 on 2021-04-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adrs', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNo', models.CharField(max_length=20)),
                ('referedBy', models.CharField(max_length=100)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_name', models.CharField(max_length=500)),
                ('qty', models.PositiveIntegerField()),
                ('t_price', models.FloatField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
