# Generated by Django 3.1.1 on 2021-04-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='trId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
